# -*- coding: utf-8 -*-
"""K-means

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lu2_2C7kPnVhJS45Vv0pJczXE9DfEQna
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)
print("Original dataset shape:", df.shape)
display(df.head())

plt.figure(figsize=(6, 4))
df["Gender"].value_counts().plot(kind="bar")
plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Number of Participants")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 4))
df["Age_Range"].value_counts().sort_index().plot(kind="bar")
plt.title("Age Range Distribution")
plt.xlabel("Age Range")
plt.ylabel("Number of Participants")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 4))
df["Perception_EatingDisorder"].value_counts().plot(kind="bar")
plt.title("Perception of Having an Eating Disorder")
plt.xlabel("Response")
plt.ylabel("Number of Participants")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.show()

sample_questions = [
    "EatLess_OnWeightGain",
    "Monitor_Food",
    "Eat_WhenAnxious",
    "Days_FeltFat",
    "Days_FearLosingControlOverEating"
]

for col in sample_questions:
    if col in df.columns:
        plt.figure(figsize=(7, 4))
        df[col].value_counts().plot(kind="bar")
        plt.title(f"Response Distribution: {col}")
        plt.xlabel("Response")
        plt.ylabel("Number of Participants")
        plt.xticks(rotation=35, ha="right")
        plt.tight_layout()
        plt.show()

frequency_map = {
    "Often": 3,
    "Sometimes": 2,
    "Seldom": 1,
    "Never": 0
}

days_map = {
    "No days": 0,
    "1-12 days": 1,
    "13-27 days": 2,
    "Every day": 3
}

belief_map = {
    "Yes, I believe I do": 1,
    "No, I don’t believe I do": 0,
    "No, I don't believe I do": 0
}

gender_map = {
    "Female": 0,
    "Male": 1
}

employment_map = {
    "Student": 0,
    "Self-employed": 1,
    "Employed part-time": 2,
    "Employed full-time": 3
}

marital_map = {
    "Single": 0,
    "In a relationship": 1,
    "Married": 2
}

age_map = {
    "18-24": 0,
    "25-34": 1
}

numeric_df = df.copy()

for col in numeric_df.columns:
    numeric_df[col] = numeric_df[col].replace(frequency_map)
    numeric_df[col] = numeric_df[col].replace(days_map)
    numeric_df[col] = numeric_df[col].replace(belief_map)
    numeric_df[col] = numeric_df[col].replace(gender_map)
    numeric_df[col] = numeric_df[col].replace(employment_map)
    numeric_df[col] = numeric_df[col].replace(marital_map)
    numeric_df[col] = numeric_df[col].replace(age_map)

numeric_df = numeric_df.apply(pd.to_numeric, errors="coerce")

numeric_only = numeric_df.select_dtypes(include=[np.number])

print("Numeric data shape:", numeric_only.shape)
display(numeric_only.head())

demo_cols = [
    "Age_Range",
    "Gender",
    "Division_ofOrigin",
    "Current_EducationLevel",
    "Employment_Status",
    "Marital_Status",
    "Perception_EatingDisorder"
]

behavioral_only = numeric_only.drop(
    columns=demo_cols,
    errors="ignore"
)

missing_before = pd.DataFrame({
    "Item": behavioral_only.columns,
    "Missing_Count": behavioral_only.isna().sum().values,
    "Nonmissing_Count": behavioral_only.notna().sum().values,
    "Percent_Nonmissing": behavioral_only.notna().mean().values * 100
})

print("Missingness before preprocessing:")
display(missing_before)

print(
    "Number of behavioral items below 80% nonmissing:",
    (missing_before["Percent_Nonmissing"] < 80).sum()
)

print(
    "Number of behavioral items with any missing values:",
    (missing_before["Missing_Count"] > 0).sum()
)

# Apply 80% completeness threshold
behavioral_only = behavioral_only.dropna(
    axis=1,
    thresh=int(0.8 * len(behavioral_only))
)



print("Behavioral-only data shape:", behavioral_only.shape)
display(behavioral_only.head())

behavioral_only.shape

plt.figure(figsize=(12, 10))
corr = behavioral_only.corr()
plt.imshow(corr, aspect="auto")
plt.colorbar(label="Correlation")
plt.title("Correlation Heatmap of Numeric Survey Responses")
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90, fontsize=6)
plt.yticks(range(len(corr.columns)), corr.columns, fontsize=6)
plt.tight_layout()
plt.show()

#helps avoid repetition for the 50-variable and 5-group model for elbow and silhouette analysis
def run_elbow_silhouette(X, title):
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    inertias = []
    silhouette_scores = []
    K_range = range(2, 11)

    for k in K_range:
        kmeans = KMeans(n_clusters=k, random_state=42, n_init=20)
        labels = kmeans.fit_predict(X_scaled)
        inertias.append(kmeans.inertia_)
        silhouette_scores.append(silhouette_score(X_scaled, labels))

    plt.figure(figsize=(7, 4))
    plt.plot(list(K_range), inertias, marker="o")
    plt.title(f"Elbow Method for Choosing K: {title}")
    plt.xlabel("Number of clusters K")
    plt.ylabel("Inertia")
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(7, 4))
    plt.plot(list(K_range), silhouette_scores, marker="o")
    plt.title(f"Silhouette Score by K: {title}")
    plt.xlabel("Number of clusters K")
    plt.ylabel("Silhouette Score")
    plt.tight_layout()
    plt.show()

    results = pd.DataFrame({
        "K": list(K_range),
        "Inertia": inertias,
        "Silhouette Score": silhouette_scores
    })

    return results, X_scaled

results_50, X_scaled_50 = run_elbow_silhouette(
    behavioral_only,
    "50 Behavioral Variables"
)

print("K evaluation results for 50 behavioral variables:")
display(results_50)

print("All behavioral columns:")
for col in behavioral_only.columns:
    print(col)

#preprocessing the data and making the data simpler into 5 groups
# 1. Restrictive Eating
restriction_cols = [
    "EatLess_OnWeightGain",
    "EatLess_AtMealtime",
    "RefuseFood_WeightConcern",
    "Eat_SlimmingFoods",
    "EatLess_AfterOvereating",
    "EatLess_ToPreventWeightGain",
    "AvoidSnacks_BetweenMealsForWeightConcern",
    "AvoidEveningEating_ForWeightConcern",
    "ConsiderWeight_WhenEating",
    "Days_TriedLimitFoodToControlShapeOrWeight",
    "Days_FastedToControlShapeOrWeight",
    "Days_ExcludedFoodToControlShapeOrWeight",
    "Days_FollowedRulesToControlShapeOrWeight"
]

# 2. Emotional Eating
emotional_cols = [
    "Eat_WhenIrritated",
    "Eat_WhenUnoccupied",
    "Eat_WhenDepressedOrDiscouraged",
    "Eat_WhenLonely",
    "Eat_WhenSomeoneLetYouDown",
    "Eat_WhenAngry",
    "Eat_WhenExpectingBad",
    "Eat_WhenAnxious",
    "Eat_WhenThingsGoWrong",
    "Eat_WhenFrightened",
    "Eat_WhenDisappointed",
    "Eat_WhenEmotionallyUpset",
    "Eat_WhenBoredOrRestless",
    "AutomaticEating_WhenExperiencingStrongEmotion"
]

# 3. External Cue / Reward Eating
external_cols = [
    "EatMore_IfFoodTasty",
    "EatMore_IfFoodSmellsOrLooksGood",
    "Eat_WhenSeeDeliciousFood",
    "Eat_DeliciousFoodImmediately",
    "DesireToBuy_FromBakery",
    "DesireToBuy _FromSnackBarOrCafe",
    "DesireToEat_WhenSeeOthersEating",
    "EatMore_WhenSeeOthersEating",
    "Eat_WhenPreparingMeal",
    "Resist_DeliciousFood"
]

# 4. Body Image / Weight Concern
body_image_cols = [
    "Monitor_Food",
    "Days_DesireForFlatStomach",
    "Days_FeltFat",
    "Days_WeightAffectedSelfJudgment",
    "Days_ShapeAffectedSelfJudgment",
    "Days_DissatisfiedWithWeight",
    "Days_DissatisfiedWithShape",
    "Days_UncomfortableToSeeOwnBody",
    "Days_UncomfortableOthersSeeingYourShape"
]

# 5. Habitual / Loss-of-Control Eating
habitual_cols = [
    "Days_FearLosingControlOverEating",
    "Eat_SpecificFoodsHabitually",
    "Location_TriggersHabitualEating",
    "Realize_AfterEatingOutOfHabit"
]

group_dict = {
    "Restrictive_Eating": restriction_cols,
    "Emotional_Eating": emotional_cols,
    "External_Cue_Eating": external_cols,
    "Body_Image_Concern": body_image_cols,
    "Habitual_LossOfControl": habitual_cols
}


# Check how many questions were assigned to each group
print("Behavioral Group Summary")
print("-" * 40)

total_questions = 0

for group, cols in group_dict.items():
    print(f"{group}: {len(cols)} questions")
    total_questions += len(cols)

print("-" * 40)
print("Total questions assigned:", total_questions)
print("Original behavioral variables:", len(behavioral_only.columns))

print("Columns included in each group:")

for group_name, cols in group_dict.items():
    print(f"\n{group_name}")
    print(f"Number of columns: {len(cols)}")
    print(cols)

behavioral_5 = pd.DataFrame(index=behavioral_only.index)

for group_name, cols in group_dict.items():
    behavioral_5[group_name] = behavioral_only[cols].mean(axis=1)

print("Five-group behavioral data shape:", behavioral_5.shape)
display(behavioral_5.head())

# Combine all behavioral items assigned to the five categories
all_grouped_items = []

for category, cols in group_dict.items():
    all_grouped_items.extend(cols)

print("Total items assigned to categories:", len(all_grouped_items))
print("Unique items assigned:", len(set(all_grouped_items)))
print("Behavioral items in dataset:", len(behavioral_only.columns))

# Check for duplicates
duplicates = [
    item for item in set(all_grouped_items)
    if all_grouped_items.count(item) > 1
]

# Check whether any behavioral variables were not assigned
unassigned = [
    col for col in behavioral_only.columns
    if col not in all_grouped_items
]

# Check whether your category lists contain variables not in the dataset
not_in_dataset = [
    col for col in all_grouped_items
    if col not in behavioral_only.columns
]

print("Duplicate assignments:", duplicates)
print("Unassigned behavioral items:", unassigned)
print("Category items not found in dataset:", not_in_dataset)

frequency_responses = {
    "Never",
    "Seldom",
    "Sometimes",
    "Often"
}

days_responses = {
    "No days",
    "1-12 days",
    "13-27 days",
    "Every day"
}

def identify_scale(column):

    responses = set(
        df[column]
        .dropna()
        .astype(str)
        .str.strip()
        .unique()
    )

    if responses.issubset(frequency_responses):
        return "Frequency"

    elif responses.issubset(days_responses):
        return "Days"

    else:
        return "Other"


scale_mapping = {}

for col in behavioral_only.columns:
    scale_mapping[col] = identify_scale(col)

print("Response-scale counts:")
display(
    pd.Series(scale_mapping)
    .value_counts()
)

def response_scale_text(scale):

    if scale == "Frequency":
        return "Never (0); Seldom (1); Sometimes (2); Often (3)"

    elif scale == "Days":
        return "No days (0); 1-12 days (1); 13-27 days (2); Every day (3)"

    else:
        return "Check original questionnaire"

publication_names = {
    "Restrictive_Eating": "Restrictive Eating",
    "Emotional_Eating": "Emotional Eating",
    "External_Cue_Eating": "External Cue Eating",
    "Body_Image_Concern": "Body Image Concern",
    "Habitual_LossOfControl": "Habitual/Loss-of-Control Eating"
}

category_lookup = {}

for category, cols in group_dict.items():
    for col in cols:
        category_lookup[col] = publication_names[category]

section_mapping = {}

# Section B: Cognitive Control
section_b = [
    "EatLess_OnWeightGain",
    "EatLess_AtMealtime",
    "RefuseFood_WeightConcern",
    "Monitor_Food",
    "Eat_SlimmingFoods",
    "EatLess_AfterOvereating",
    "EatLess_ToPreventWeightGain",
    "AvoidSnacks_BetweenMealsForWeightConcern",
    "AvoidEveningEating_ForWeightConcern",
    "ConsiderWeight_WhenEating"
]

# Section C: Affective Value Representation
section_c = [
    "Eat_WhenIrritated",
    "Eat_WhenUnoccupied",
    "Eat_WhenDepressedOrDiscouraged",
    "Eat_WhenLonely",
    "Eat_WhenSomeoneLetYouDown",
    "Eat_WhenAngry",
    "Eat_WhenExpectingBad",
    "Eat_WhenAnxious",
    "Eat_WhenThingsGoWrong",
    "Eat_WhenFrightened",
    "Eat_WhenDisappointed",
    "Eat_WhenEmotionallyUpset",
    "Eat_WhenBoredOrRestless"
]

# Section D: Salience/Taste Processing
section_d = [
    "EatMore_IfFoodTasty",
    "EatMore_IfFoodSmellsOrLooksGood",
    "Eat_WhenSeeDeliciousFood",
    "Eat_DeliciousFoodImmediately",
    "DesireToBuy_FromBakery",
    "DesireToBuy _FromSnackBarOrCafe",
    "DesireToEat_WhenSeeOthersEating",
    "Resist_DeliciousFood",
    "EatMore_WhenSeeOthersEating",
    "Eat_WhenPreparingMeal"
]

# Section E: Body Image Processing
section_e = [
    "Days_DesireForFlatStomach",
    "Days_FeltFat",
    "Days_WeightAffectedSelfJudgment",
    "Days_ShapeAffectedSelfJudgment",
    "Days_DissatisfiedWithWeight",
    "Days_DissatisfiedWithShape",
    "Days_UncomfortableToSeeOwnBody",
    "Days_UncomfortableOthersSeeingYourShape"
]

# Section F: Reward Processing/Habit Formation
section_f = [
    "Days_TriedLimitFoodToControlShapeOrWeight",
    "Days_FastedToControlShapeOrWeight",
    "Days_ExcludedFoodToControlShapeOrWeight",
    "Days_FollowedRulesToControlShapeOrWeight",
    "Days_FearLosingControlOverEating",
    "Eat_SpecificFoodsHabitually",
    "Location_TriggersHabitualEating",
    "AutomaticEating_WhenExperiencingStrongEmotion",
    "Realize_AfterEatingOutOfHabit"
]

for col in section_b:
    section_mapping[col] = "Section B: Cognitive Control"

for col in section_c:
    section_mapping[col] = "Section C: Affective Value Representation"

for col in section_d:
    section_mapping[col] = "Section D: Salience/Taste Processing"

for col in section_e:
    section_mapping[col] = "Section E: Body Image Processing"

for col in section_f:
    section_mapping[col] = "Section F: Reward Processing/Habit Formation"

appendix_rows = []

item_number = 1

for category, cols in group_dict.items():

    for col in cols:

        scale = scale_mapping[col]

        appendix_rows.append({
            "Item_Number": item_number,
            "Dataset_Variable": col,
            "Exact_Questionnaire_Item": "",
            "Original_Survey_Section": section_mapping[col],
            "Behavioral_Category": publication_names[category],
            "Response_Scale": response_scale_text(scale),
            "Minimum_Score": 0,
            "Maximum_Score": 3
        })

        item_number += 1


appendix_table = pd.DataFrame(appendix_rows)

print("Appendix Table A1:")
display(appendix_table)

print("Number of rows:", len(appendix_table))

appendix_table.to_csv(
    "Appendix_Table_A1.csv",
    index=False
)

print("Appendix_Table_A1.csv created.")

from google.colab import files

files.download("Appendix_Table_A1.csv")

results_5, X_scaled_5 = run_elbow_silhouette(
    behavioral_5,
    "5 Averaged Behavioral Groups"
)

print("K evaluation results for 5 averaged behavioral groups:")
display(results_5)

kmeans_2 = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=20
)

labels_2 = kmeans_2.fit_predict(X_scaled_5)


kmeans_3 = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=20
)

labels_3 = kmeans_3.fit_predict(X_scaled_5)

silhouette_2 = silhouette_score(X_scaled_5, labels_2)
silhouette_3 = silhouette_score(X_scaled_5, labels_3)

comparison_k = pd.DataFrame({
    "K": [2, 3],
    "Inertia": [
        kmeans_2.inertia_,
        kmeans_3.inertia_
    ],
    "Silhouette_Score": [
        silhouette_2,
        silhouette_3
    ]
})

print("Direct comparison of K=2 and K=3:")
display(comparison_k.round(4))

print("K=2 cluster sizes:")
display(
    pd.Series(labels_2)
    .value_counts()
    .sort_index()
    .rename_axis("Cluster")
    .reset_index(name="Participants")
)

print("K=3 cluster sizes:")
display(
    pd.Series(labels_3)
    .value_counts()
    .sort_index()
    .rename_axis("Cluster")
    .reset_index(name="Participants")
)

behavioral_k2 = behavioral_5.copy()

behavioral_k2["Cluster"] = labels_2 + 1

cluster_means_k2 = (
    behavioral_k2
    .groupby("Cluster")
    .mean()
)

print("Average behavioral scores for K=2:")
display(cluster_means_k2.round(2))

behavioral_k3 = behavioral_5.copy()

behavioral_k3["Cluster"] = labels_3 + 1

cluster_means_k3 = (
    behavioral_k3
    .groupby("Cluster")
    .mean()
)

print("Average behavioral scores for K=3:")
display(cluster_means_k3.round(2))

# Fit K=2
kmeans_2 = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=20
)

labels_2 = kmeans_2.fit_predict(X_scaled_5)


# Fit K=3
kmeans_3 = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=20
)

labels_3 = kmeans_3.fit_predict(X_scaled_5)


# Compare inertia and silhouette score


silhouette_2 = silhouette_score(X_scaled_5, labels_2)
silhouette_3 = silhouette_score(X_scaled_5, labels_3)

comparison_k = pd.DataFrame({
    "K": [2, 3],
    "Inertia": [
        kmeans_2.inertia_,
        kmeans_3.inertia_
    ],
    "Silhouette_Score": [
        silhouette_2,
        silhouette_3
    ]
})

print("K=2 versus K=3:")
display(comparison_k.round(4))


#  Cluster sizes

print("K=2 cluster sizes:")
display(
    pd.Series(labels_2 + 1)
    .value_counts()
    .sort_index()
)

print("K=3 cluster sizes:")
display(
    pd.Series(labels_3 + 1)
    .value_counts()
    .sort_index()
)


# Behavioral profiles for K=2

behavioral_k2 = behavioral_5.copy()
behavioral_k2["Cluster"] = labels_2 + 1

cluster_means_k2 = (
    behavioral_k2
    .groupby("Cluster")
    .mean()
)

print("K=2 behavioral profiles:")
display(cluster_means_k2.round(2))


# Behavioral profiles for K=3

behavioral_k3 = behavioral_5.copy()
behavioral_k3["Cluster"] = labels_3 + 1

cluster_means_k3 = (
    behavioral_k3
    .groupby("Cluster")
    .mean()
)

print("K=3 behavioral profiles:")
display(cluster_means_k3.round(2))

# Compare participant assignments between K=2 and K=3

k_comparison_df = pd.DataFrame({
    "K2_Cluster": labels_2 + 1,
    "K3_Cluster": labels_3 + 1
})

k2_k3_counts = pd.crosstab(
    k_comparison_df["K2_Cluster"],
    k_comparison_df["K3_Cluster"]
)

print("K=2 vs K=3 participant assignments:")
display(k2_k3_counts)


# Percentage version


k2_k3_percent = pd.crosstab(
    k_comparison_df["K2_Cluster"],
    k_comparison_df["K3_Cluster"],
    normalize="index"
) * 100

print("Percentage of each K=2 cluster assigned to K=3 clusters:")
display(k2_k3_percent.round(1))


# Overall behavioral score by cluster

overall_score = behavioral_5.mean(axis=1)

overall_k2 = pd.DataFrame({
    "Overall_Behavioral_Score": overall_score,
    "Cluster": labels_2 + 1
})

overall_k3 = pd.DataFrame({
    "Overall_Behavioral_Score": overall_score,
    "Cluster": labels_3 + 1
})

print("Overall behavioral score for K=2:")
display(
    overall_k2
    .groupby("Cluster")
    ["Overall_Behavioral_Score"]
    .mean()
    .round(2)
)

print("Overall behavioral score for K=3:")
display(
    overall_k3
    .groupby("Cluster")
    ["Overall_Behavioral_Score"]
    .mean()
    .round(2)
)

#comparison of elbow and silhouette score
comparison_results = pd.DataFrame({
    "K": results_50["K"],
    "Inertia_50_Variables": results_50["Inertia"],
    "Silhouette_50_Variables": results_50["Silhouette Score"],
    "Inertia_5_Groups": results_5["Inertia"],
    "Silhouette_5_Groups": results_5["Silhouette Score"]
})

print("Comparison of K evaluation results:")
display(comparison_results)

print("Highest silhouette score for 50-variable model:",
      comparison_results["Silhouette_50_Variables"].max())

print("Highest silhouette score for 5-group model:",
      comparison_results["Silhouette_5_Groups"].max())

print("Silhouette score improvement after preprocessing:",
      comparison_results["Silhouette_5_Groups"].max()
      - comparison_results["Silhouette_50_Variables"].max())

chosen_k = 3

kmeans_50 = KMeans(n_clusters=chosen_k, random_state=42, n_init=20)
labels_50 = kmeans_50.fit_predict(X_scaled_50)

kmeans_5 = KMeans(n_clusters=chosen_k, random_state=42, n_init=20)
labels_5 = kmeans_5.fit_predict(X_scaled_5)

df_results = df.copy()
df_results["Cluster_50_Variables"] = labels_50
df_results["Cluster_5_Groups"] = labels_5

df_results["Cluster"] = labels_5 + 1

print("Cluster counts for 50-variable model:")
display(df_results["Cluster_50_Variables"].value_counts().sort_index())

print("Cluster counts for 5-group model:")
display(df_results["Cluster_5_Groups"].value_counts().sort_index())

#interpret the 5-group clusters
cluster_summary_5 = behavioral_5.copy()
cluster_summary_5["Cluster"] = labels_5+1

cluster_means_5 = cluster_summary_5.groupby("Cluster").mean()

print("Average behavioral group scores by cluster:")
display(cluster_means_5.round(2))

plt.figure(figsize=(8,5))
plt.imshow(cluster_means_5, aspect="auto")
plt.colorbar(label="Average Score")
plt.title("Cluster Profiles Using 5 Averaged Behavioral Groups")
plt.xticks(
    range(len(cluster_means_5.columns)),
    cluster_means_5.columns,
    rotation=45,
    ha="right"
)
plt.yticks(
    range(len(cluster_means_5.index)),
    [f"Cluster {i}" for i in cluster_means_5.index]
)
plt.tight_layout()
plt.show()

# ABOVE-MIDPOINT ANALYSIS

midpoint = 1.5

above_midpoint_data = behavioral_5.copy()
above_midpoint_data["Cluster"] = df_results["Cluster"]

for cluster in [1, 2, 3]:

    cluster_data = above_midpoint_data[
        above_midpoint_data["Cluster"] == cluster
    ].drop(columns="Cluster")

    print(f"\nCLUSTER {cluster}")
    print("-" * 40)

    category_percentages = (
        (cluster_data > midpoint)
        .mean()
        * 100
    )

    print("Percentage above midpoint by category:")
    print(category_percentages.round(1))

    categories_above_midpoint = (
        cluster_data > midpoint
    ).sum(axis=1)

    percent_3_or_more = (
        (categories_above_midpoint >= 3).mean()
        * 100
    )

    percent_4_or_more = (
        (categories_above_midpoint >= 4).mean()
        * 100
    )

    print(
        "Above midpoint on 3 or more categories:",
        round(percent_3_or_more, 1),
        "%"
    )

    print(
        "Above midpoint on 4 or more categories:",
        round(percent_4_or_more, 1),
        "%"
    )

# RADAR CHART OF THE THREE BEHAVIORAL CLUSTER PROFILES

from math import pi

radar_data = cluster_means_5.copy()

radar_labels = [
    "Restrictive Eating",
    "Emotional Eating",
    "External Cue Eating",
    "Body Image Concern",
    "Habitual/Loss-of-Control Eating"
]

number_of_categories = len(radar_labels)

angles = [
    n / float(number_of_categories) * 2 * pi
    for n in range(number_of_categories)
]

angles += angles[:1]

fig, ax = plt.subplots(
    figsize=(9, 8),
    subplot_kw={"polar": True}
)

for cluster in radar_data.index:
    values = radar_data.loc[cluster].tolist()
    values += values[:1]

    ax.plot(
        angles,
        values,
        linewidth=2,
        label=f"Cluster {cluster}"
    )

    ax.fill(
        angles,
        values,
        alpha=0.10
    )

ax.set_xticks(angles[:-1])
ax.set_xticklabels(
    radar_labels,
    fontsize=10
)

ax.set_ylim(0, 3)

ax.set_yticks([
    0.5,
    1.0,
    1.5,
    2.0,
    2.5,
    3.0
])



ax.legend(
    title="Behavioral Group",
    loc="upper right",
    bbox_to_anchor=(1.35, 1.15)
)

plt.tight_layout()
plt.show()

response_distribution_rows = []

for category, cols in group_dict.items():

    for cluster in [1, 2, 3]:

        cluster_indices = df_results.index[
            df_results["Cluster"] == cluster
        ]

        category_data = behavioral_only.loc[
            cluster_indices,
            cols
        ]

        values = category_data.to_numpy().flatten()

        for score in [0, 1, 2, 3]:

            percentage = (
                np.sum(values == score) / len(values)
            ) * 100

            response_distribution_rows.append({
                "Behavioral_Category": publication_names[category],
                "Cluster": cluster,
                "Response_Score": score,
                "Percentage": percentage
            })


response_distribution = pd.DataFrame(
    response_distribution_rows
)

print("Percentage distribution of item-level responses:")
display(response_distribution.round(1))

percentage_check = (
    response_distribution
    .groupby(
        ["Behavioral_Category", "Cluster"]
    )["Percentage"]
    .sum()
)

print("Check that percentages sum to 100%:")
display(percentage_check.round(2))

# Create 100% stacked bar chart

categories = [
    publication_names[category]
    for category in group_dict.keys()
]

clusters = [1, 2, 3]
scores = [0, 1, 2, 3]

x = np.arange(len(categories))

bar_width = 0.25

fig, ax = plt.subplots(figsize=(14, 7))


for cluster_index, cluster in enumerate(clusters):

    bottom = np.zeros(len(categories))

    positions = (
        x + (cluster_index - 1) * bar_width
    )

    for score in scores:

        percentages = []

        for category in categories:

            value = response_distribution.loc[
                (
                    response_distribution[
                        "Behavioral_Category"
                    ] == category
                )
                &
                (
                    response_distribution[
                        "Cluster"
                    ] == cluster
                )
                &
                (
                    response_distribution[
                        "Response_Score"
                    ] == score
                ),
                "Percentage"
            ].iloc[0]

            percentages.append(value)

        ax.bar(
            positions,
            percentages,
            width=bar_width,
            bottom=bottom,
            label=(
                f"Score {score}"
                if cluster == 1
                else None
            )
        )

        bottom += np.array(percentages)


ax.set_ylabel("Percentage of Item Responses (%)")

ax.set_xlabel("Behavioral Category")

ax.set_title(
    "Distribution of Response Scores by Behavioral Category and Cluster"
)

ax.set_xticks(x)

ax.set_xticklabels(
    categories,
    rotation=20,
    ha="right"
)

ax.set_ylim(0, 100)

ax.legend(
    title="Response Score",
    bbox_to_anchor=(1.02, 1),
    loc="upper left"
)

plt.tight_layout()

plt.savefig(
    "Figure2_Response_Distributions.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

#comparison of participant cluster assignments between both approaches
cluster_comparison = pd.crosstab(
    df_results["Cluster_50_Variables"],
    df_results["Cluster_5_Groups"],
    rownames=["50 Variable Clusters"],
    colnames=["5 Group Clusters"]
)

print("Comparison of cluster assignments:")
display(cluster_comparison)

print("Number of participants in each cluster:")

cluster_counts = (
    df_results["Cluster"]
    .value_counts()
    .sort_index()
)

display(cluster_counts)

demographic_variables = [
    "Gender",
    "Age_Range",
    "Current_EducationLevel",
    "Employment_Status",
    "Marital_Status"
]

for variable in demographic_variables:

    print("\n===================================")
    print("Overall:", variable)
    print("===================================")

    overall_counts = df_results[variable].value_counts(
        dropna=False
    )

    overall_percentages = (
        df_results[variable]
        .value_counts(
            normalize=True,
            dropna=False
        ) * 100
    )

    overall_summary = pd.DataFrame({
        "Count": overall_counts,
        "Percent": overall_percentages
    })

    display(overall_summary.round(1))

# Demographic counts and percentages within each cluster

for variable in demographic_variables:

    print("\n===================================")
    print("By cluster:", variable)
    print("===================================")

    counts = pd.crosstab(
        df_results[variable],
        df_results["Cluster"]
    )

    percentages = (
        pd.crosstab(
            df_results[variable],
            df_results["Cluster"],
            normalize="columns"
        ) * 100
    )

    print("Counts:")
    display(counts)

    print("Percentages within each cluster:")
    display(percentages.round(1))

def format_n_percent(count, total):

    if total == 0:
        return "0 (0.0%)"

    percent = (count / total) * 100

    return f"{count} ({percent:.1f}%)"

# Existing p-values already reported in the manuscript

existing_p_values = {
    "Gender": ".252",
    "Age_Range": ".680",
    "Current_EducationLevel": ".887",
    "Employment_Status": ".503",
    "Marital_Status": ".268"
}

display_names = {
    "Gender": "Gender",
    "Age_Range": "Age range",
    "Current_EducationLevel": "Education level",
    "Employment_Status": "Employment status",
    "Marital_Status": "Marital status"
}

# BUILD TABLE 1

table1_rows = []

for variable in demographic_variables:

    # Add the main demographic-variable heading
    table1_rows.append({
        "Characteristic": display_names[variable],
        "Overall": "",
        "Cluster 1": "",
        "Cluster 2": "",
        "Cluster 3": "",
        "p-value": existing_p_values[variable],
        "Cramer's V": ""
    })

    # Get all response categories actually present
    categories = df_results[variable].dropna().unique()

    # Overall denominator
    overall_total = df_results[variable].notna().sum()

    for category in categories:

        # Overall count
        overall_count = (
            df_results[variable] == category
        ).sum()

        # Cluster-specific values
        cluster_results = {}

        for cluster in [1, 2, 3]:

            cluster_data = df_results[
                df_results["Cluster"] == cluster
            ]

            cluster_total = (
                cluster_data[variable]
                .notna()
                .sum()
            )

            cluster_count = (
                cluster_data[variable] == category
            ).sum()

            cluster_results[cluster] = format_n_percent(
                cluster_count,
                cluster_total
            )

        table1_rows.append({
            "Characteristic": "  " + str(category),
            "Overall": format_n_percent(
                overall_count,
                overall_total
            ),
            "Cluster 1": cluster_results[1],
            "Cluster 2": cluster_results[2],
            "Cluster 3": cluster_results[3],
            "p-value": "",
            "Cramer's V": ""
        })


table1 = pd.DataFrame(table1_rows)

display(table1)

table1.to_csv(
    "Table1_Demographic_Characteristics.csv",
    index=False
)

print("Table 1 saved successfully.")

from google.colab import files

files.download(
    "Table1_Demographic_Characteristics.csv"
)

gender_counts = pd.crosstab(
    df_results["Cluster"],
    df_results["Gender"]
)

gender_percentages = pd.crosstab(
    df_results["Cluster"],
    df_results["Gender"],
    normalize="index"
) * 100

print("Gender counts by cluster:")
display(gender_counts)

print("Gender percentages within each cluster:")
display(gender_percentages.round(1))

gender_percentages.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Gender Distribution Within Each Cluster")
plt.xlabel("Cluster")
plt.ylabel("Percentage of Participants")
plt.xticks(rotation=0)
plt.legend(title="Gender")
plt.tight_layout()
plt.show()

age_counts = pd.crosstab(
    df_results["Cluster"],
    df_results["Age_Range"]
)

age_percentages = pd.crosstab(
    df_results["Cluster"],
    df_results["Age_Range"],
    normalize="index"
) * 100

print("Age-range counts by cluster:")
display(age_counts)

print("Age-range percentages within each cluster:")
display(age_percentages.round(1))

age_percentages.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Age-Range Distribution Within Each Cluster")
plt.xlabel("Cluster")
plt.ylabel("Percentage of Participants")
plt.xticks(rotation=0)
plt.legend(title="Age Range")
plt.tight_layout()
plt.show()

education_counts = pd.crosstab(
    df_results["Cluster"],
    df_results["Current_EducationLevel"]
)

education_percentages = pd.crosstab(
    df_results["Cluster"],
    df_results["Current_EducationLevel"],
    normalize="index"
) * 100

print("Education-level counts by cluster:")
display(education_counts)

print("Education-level percentages within each cluster:")
display(education_percentages.round(1))

education_percentages.plot(
    kind="bar",
    figsize=(10, 5)
)

plt.title("Education-Level Distribution Within Each Cluster")
plt.xlabel("Cluster")
plt.ylabel("Percentage of Participants")
plt.xticks(rotation=0)
plt.legend(
    title="Education Level",
    bbox_to_anchor=(1.05, 1),
    loc="upper left"
)
plt.tight_layout()
plt.show()

employment_counts = pd.crosstab(
    df_results["Cluster"],
    df_results["Employment_Status"]
)

employment_percentages = pd.crosstab(
    df_results["Cluster"],
    df_results["Employment_Status"],
    normalize="index"
) * 100

print("Employment-status counts by cluster:")
display(employment_counts)

print("Employment-status percentages within each cluster:")
display(employment_percentages.round(1))

from sklearn.metrics import adjusted_rand_score

marital_counts = pd.crosstab(
    df_results["Cluster"],
    df_results["Marital_Status"]
)

marital_percentages = pd.crosstab(
    df_results["Cluster"],
    df_results["Marital_Status"],
    normalize="index"
) * 100

print("Marital-status counts by cluster:")
display(marital_counts)

print("Marital-status percentages within each cluster:")
display(marital_percentages.round(1))

from scipy.stats import chi2_contingency

demographic_variables = {
    "Gender": [
        "Female",
        "Male"
    ],

    "Age range": [
        "18-24",
        "25-34"
    ],

    "Education level": [
        "Bachelor's degree 1st year",
        "Bachelor's degree 2nd year",
        "Bachelor's degree 3rd year",
        "Bachelor's degree 4th year",
        "Master's degree 1st year",
        "Master's degree 2nd year"
    ],

    "Employment status": [
        "Student",
        "Self-employed",
        "Employed part-time",
        "Employed full-time"
    ],

    "Marital status": [
        "Single",
        "In a relationship",
        "Married"
    ]
}

dataset_columns = {
    "Gender": "Gender",
    "Age range": "Age_Range",
    "Education level": "Current_EducationLevel",
    "Employment status": "Employment_Status",
    "Marital status": "Marital_Status"
}


def format_n_percent(count, total):
    if total == 0:
        return "0 (0.0%)"

    percent = count / total * 100

    return f"{count} ({percent:.1f}%)"


# Format p-values for publication
def format_p_value(p):
    if p < 0.001:
        return "< .001"
    return f"{p:.3f}"


# Calculate Cramer's V
def cramers_v(contingency_table):

    chi2, p, dof, expected = chi2_contingency(
        contingency_table
    )

    n = contingency_table.to_numpy().sum()

    rows, columns = contingency_table.shape

    v = np.sqrt(
        chi2 /
        (
            n *
            min(rows - 1, columns - 1)
        )
    )

    return chi2, p, dof, v

# =========================================================
# CHI-SQUARE TESTS AND CRAMER'S V FOR DEMOGRAPHIC VARIABLES
# =========================================================

demographic_columns = [
    "Gender",
    "Age_Range",
    "Current_EducationLevel",
    "Employment_Status",
    "Marital_Status"
]

demographic_test_results = []

for variable in demographic_columns:

    # Create contingency table:
    # demographic categories x final 3-cluster assignments
    contingency_table = pd.crosstab(
        df_results[variable],
        df_results["Cluster"]
    )

    # Calculate chi-square and Cramer's V
    chi2, p, dof, v = cramers_v(contingency_table)

    demographic_test_results.append({
        "Variable": variable,
        "Chi_square": chi2,
        "df": dof,
        "p_value": p,
        "Cramers_V": v
    })

demographic_test_results = pd.DataFrame(
    demographic_test_results
)

print("Demographic chi-square tests and Cramer's V:")
display(
    demographic_test_results.round({
        "Chi_square": 2,
        "p_value": 3,
        "Cramers_V": 3
    })
)

reference_labels = labels_5.copy()

stability_scores = []

for seed in range(100):
    repeated_kmeans = KMeans(
        n_clusters=3,
        random_state=seed,
        n_init=20
    )

    repeated_labels = repeated_kmeans.fit_predict(X_scaled_5)

    stability_score = adjusted_rand_score(
        reference_labels,
        repeated_labels
    )

    stability_scores.append(stability_score)

stability_results = pd.DataFrame({
    "Random_Seed": range(100),
    "Adjusted_Rand_Index": stability_scores
})

print("Stability results:")
display(stability_results)

print(
    "Average stability score:",
    round(stability_results["Adjusted_Rand_Index"].mean(), 3)
)

print(
    "Minimum stability score:",
    round(stability_results["Adjusted_Rand_Index"].min(), 3)
)

print(
    "Maximum stability score:",
    round(stability_results["Adjusted_Rand_Index"].max(), 3)
)

plt.figure(figsize=(9, 5))

plt.plot(
    stability_results["Random_Seed"],
    stability_results["Adjusted_Rand_Index"],
    marker="o",
    markersize=3
)


plt.title("Stability of the Three-Cluster Solution")
plt.xlabel("Random Seed")
plt.ylabel("Adjusted Rand Index")
plt.ylim(0, 1.05)
plt.legend()
plt.tight_layout()
plt.show()

